### PR TITLE
Docs update 0.8.x

### PR DESCRIPTION
**Pull request by hferrone**

### CODE REVIEW

**Comment by hferrone** [comment]
@luis-valverde-ms Can you preview these in docfx on your end and answer the comments I left in README.md, Docs/WelcomeToMRTK.md and Docs/Installation.md?

**Review by macborow — COMMENTED** [review]
.DS_Store file should not be submitted - perhaps we should add it to .gitignore? @luis-valverde-ms

**Comment by luis-valverde-ms** [comment]
> .DS_Store file should not be submitted - perhaps we should add it to .gitignore? @luis-valverde-ms

Good catch @macborow . Will add. I'm creating ADO PRs for this and the 0.9x PRs. Let's continue the conversation there

**Comment by luis-valverde-ms** [comment]
@hferrone , I don't think we have that many users in 0.8. Do you think it is worth re-making these changes in ADO?

**Comment by hferrone** [comment]
@luis-valverde-ms No, I don't think that's necessary.

**Pull request closed without merging**
